### PR TITLE
Mark package as noarch and rerender using conda-smithy

### PR DESCRIPTION
**Pull request by maxnoe**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by maxnoe** [comment]
This will fix [#45](https://github.com/jcb91/jupyter_highlight_selected_word/issues/45)

**Comment by xhochy** [comment]
Does it maybe need a `notebook<7` pin?

**Comment by cerbaro** [comment]
Hey there, I am also facing [#45](https://github.com/jcb91/jupyter_highlight_selected_word/issues/45). Any progress on this review? tks!

**Comment by xhochy** [comment]
@conda-forge-admin please rerender

**Pull request merged**
